### ISSUE TITLE
v0.7.7 release?

### ISSUE THREAD

**Issue by saifelse** [bcicen/ctop#289]
Hi there,

I'm interested in the v0.7.7 release to resolve the issue fixed by https://github.com/bcicen/ctop/pull/281 . 

As I see no open issues for the [0.7.7 milestone](https://github.com/bcicen/ctop/milestone/11), are there any blockers for getting that out? If there are, I'd be happy to help!

Thanks!

**Comment by Flova** [comment]
I would also look forward to this.

**Comment by PriamX** [comment]
+1

**Comment by Flova** [comment]
I look very much forward to this, but i would like to have #287 included, since the newly added uptime collum (#212) would be broken (#275) otherwise.

**Comment by Flova** [comment]
Friendly ping @bcicen :)

**Comment by bcicen** [comment]
[v0.7.7 is now released](https://github.com/bcicen/ctop/releases/tag/v0.7.7) :)

**Comment by ovizii** [comment]
don't forget to update your installation instructions. ;-)

**Comment by bcicen** [comment]
done; thanks @ovizii :)

**Comment by ovizii** [comment]
almost done. You are still missing a "v" 
https://github.com/bcicen/ctop/releases/download/0.7.7/ctop-0.7.7-linux-amd64 

vs 

https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64

**Comment by bcicen** [comment]
of course; thanks again @ovizii !

**Comment by PriamX** [comment]
Nice. Thanks!
